import { Figtree as font } from "next/font/google";
import "./globals.css";

const inter = font({ subsets: ["latin"] });

export const metadata = {
  title: "Example of next.js",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
